num_classes: 4

# Training Configuration
training:

    batch_size: 1
    display_iters: 2
    iter_size: 9

    # Dataset Configuration
    dataset:
        name: 'slim_dataset'
        params:
            root: '/home/davidgj/projects/APR_TAX_RWY_1500'
            augmentations:
                - pca:
                    sigma_pca: 0.05   
                - random_flip:
                - choice:
                    - rotate:
                        sigma_angle: 17.0
                        w: 1185
                        h: 641
                    - random_crop:
                        w: 1185
                        h: 641

    # LR Schedule Configuration
    scheduler:
        name: 'poly_lr'
        params:
            max_iter: 50000
            decay_iter: 1
            gamma: 0.9

    # Model Configuration
    model:
        name: 'deeplabv3+1'
        stride: 8
            

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 3

    val_expers:

        - name: 'res1500_s16'
          dataset:
            name: 'slim_dataset'
            params:
                root: '/home/davidgj/projects/APR_TAX_RWY_1500'
                train: False
          model:
            name: 'deeplabv3+1'
            stride: 8




