num_classes: 4

# Training Configuration
training:

    batch_size: 2
    display_iters: 2
    iter_size: 5

    # Dataset Configuration
    dataset:
        name: 'multitask'
        params:
            root: '/home/davidgj/projects/APR_TAX_RWY'
            augmentations:
                - pca:
                    sigma_pca: 0.05   
                - random_flip:
                - choice:
                    - rotate:
                        sigma_angle: 17.0
                        w: 833
                        h: 417
                    - random_crop:
                        w: 833
                        h: 417

    # LR Schedule Configuration
    scheduler:
        name: 'poly_lr'
        params:
            max_iter: 50000
            decay_iter: 1
            gamma: 0.9

    aux_loss: True
    loss: 'multitask'

    # Model Configuration
    model:
        name: 'deeplabv3+1'
        stride: 8
            

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 1

    val_expers:

        - name: 'res1000_s8'
          dataset:
            name: 'slim_dataset'
            params:
                root: '/home/davidgj/projects/APR_TAX_RWY'
                train: False
          model:
            name: 'deeplabv3+1'
            stride: 8
            predict: 'line_dect'

        # - name: 'res1000_s8_video'
        #   dataset:
        #     name: 'video_dataset'
        #     params:
        #         video_path: '/home/davidgj/projects/videos_aerodromo/PCI-RWY-20-3-90-001Marugan.MOV'
        #         start_time: '0:25'
        #         end_time: '0:50'
        #         camera_name: "DJI"
        #   save_path: 'PCI-RWY-20-3-90-001Marugan-seg.MOV'
        #   model:
        #     name: 'deeplabv3+1'
        #     stride: 4

        # - name: 'res1000_s8_video'
        #   dataset:
        #     name: 'video_dataset'
        #     params:
        #         video_path: '/home/davidgj/projects/videos/APR-25-5-90-004.MOV'
        #         start_time: '0:25'
        #         end_time: '1:10'
        #         camera_name: "zenmuseZ3"
        #   save_path: 'APR-25-5-90-004-seg.MOV'
        #   model:
        #     name: 'deeplabv3+1'
        #     stride: 4
        #     predict: 'line_dect'

video:

    videos-info:
        - name: "Marugan"
          checkpoint: "APR_TAX_RWY/partition_1"
          params:
            video_path: '/home/davidgj/projects/videos_aerodromo/PCI-RWY-20-3-90-001Marugan.MOV'
            start_time: '0:25'
            end_time: '0:50'
            camera_name: "DJI"

        - name: "APR-004"
          checkpoint: "APR_TAX_RWY/partition_3"
          params:
            video_path: '/home/davidgj/projects/videos/APR-25-5-90-004.MOV'
            start_time: '0:25'
            end_time: '0:30'
            # end_time: '1:10'
            camera_name: "zenmuseZ3"
    
    expers:

        - name: 's4'
          model:
            name: 'deeplabv3+1'
            stride: 4

        - name: 's4-line'
          model:
            name: 'deeplabv3+1'
            stride: 4
            predict: 'line_dect'

        - name: 's8'
          model:
            name: 'deeplabv3+1'
            stride: 8

        - name: 's8-line'
          model:
            name: 'deeplabv3+1'
            stride: 8
            predict: 'line_dect'