num_classes: 4

# Training Configuration
training:

    batch_size: 1
    display_iters: 2
    iter_size: 9

    # Dataset Configuration
    dataset:
        name: 'base_dataset'
        params:
            root: '/home/davidgj/projects/APR_TAX_RWY_2000'
            masks_test: False
            augmentations:
                - pca:
                    sigma_pca: 0.05   
                - random_flip:
                - choice:
                    - rotate:
                        sigma_angle: 17.0
                        w: 1633
                        h: 801
                    - random_crop:
                       w: 1633
                       h: 801

    # LR Schedule Configuration
    scheduler:
        name: 'poly_lr'
        params:
            max_iter: 50000
            decay_iter: 1
            gamma: 0.9

    # Model Configuration
    model:
        name: 'deeplabv3+1'
        stride: 16
            

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 3

    val_expers:

        # - name: 'res2000_s8'
        #   dataset:
        #     name: 'base_dataset'
        #     params:
        #         root: '/home/davidgj/projects/APR_TAX_RWY_2000'
        #         masks_test: True
        #   model:
        #     name: 'deeplabv3+1'
        #     stride: 8

        # - name: 'res2000_s4'
        #   dataset:
        #     name: 'base_dataset'
        #     params:
        #         root: '/home/davidgj/projects/APR_TAX_RWY_2000'
        #         masks_test: True
        #   model:
        #     name: 'deeplabv3+1'
        #     stride: 4

        - name: 'res2000_s16'
          dataset:
            name: 'slim_dataset'
            params:
                root: '/home/davidgj/projects/APR_TAX_RWY_2000'
                train: False
          model:
            name: 'deeplabv3+1'
            stride: 16
            predict: 'erode'




