num_classes: 4

# Training Configuration
training:

    batch_size: 2
    display_iters: 2
    iter_size: 5

    # Dataset Configuration
    dataset:
        name: 'base_dataset'
        params:
            root: '/home/davidgj/projects/APR_TAX_RWY'
            masks_test: False
            augmentations:
                - pca:
                    sigma_pca: 0.05   
                - random_flip:
                - choice:
                    - rotate:
                        sigma_angle: 17.0
                        w: 833
                        h: 417
                    - random_crop:
                        w: 833
                        h: 417

    # LR Schedule Configuration
    scheduler:
        name: 'poly_lr'
        params:
            max_iter: 50000
            decay_iter: 1
            gamma: 0.9

    aux_loss: True

    # Model Configuration
    model:
        name: 'deeplabv3+1'
        stride: 8
            

# Validation Configuration
validation:

    batch_size: 1
    val_epochs: 2

    val_expers:

        - name: 'res1000_s8'
          dataset:
            name: 'slim_dataset'
            params:
                root: '/home/davidgj/projects/APR_TAX_RWY'
                train: False
          model:
            name: 'deeplabv3+1'
            stride: 8

        - name: 'res1000_s4'
          dataset:
            name: 'slim_dataset'
            params:
                root: '/home/davidgj/projects/APR_TAX_RWY'
                train: False
          model:
            name: 'deeplabv3+1'
            stride: 4




